---
- name: Install Docker and run container
  hosts: Servers
  become: yes
  tasks:
    - name: Pull Nginx container from Docker Hub
      docker_image:
        name: saliibrahem/flusk:v0.1
        source: pull

    - name: Run Nginx container
      docker_container:
        name: flusk
        image: saliibrahem/flusk:v0.1
        state: started
        restart_policy: always
        ports:
          - "8080:8000"
